name: Order CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build and Test Order
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Order.API.sln

      - name: Build solution
        run: dotnet build Order.API.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Order.API.sln --configuration Release --no-build --verbosity normal